language: cpp

matrix:
  include:
    - name: "Windows"
      os: windows
    - name: "Linux"
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - ocl-icd-opencl-dev
    - name: "Linux arm64"
      os: linux
      arch: arm64
      dist: bionic
      addons:
        apt:
          packages:
            - ocl-icd-opencl-dev
    - name: "OSX"
      os: osx

before_script:
  - git submodule update --init --recursive --remote
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -G "Visual Studio 15 2017 Win64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake .. ; fi
  - cmake --build . --config Release
  - ctest -VV
  - cmake --build . --config Release --target package

branches:
  except:
    - dev

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: nWkv1F4ZP3YRWiS3g6mYWViOsijmVErbyPBdM1rn5qvai44OJxPRzoa3d24hxTJ7I+RARWxL7GFCVW5+nHOllJImL1TEWi4dMhxxwg6HyMvVKx1rS2RrHhM3kAeF4E9dAharBHi/6ecd3SvPNMdp7tsPxfMjmAVrspkSiD8ynlqT3qsDlB8TYg4ASgTniUJjxzVx5RAfR+Xja5pYctWQW++1ihKbtddtTlKxkV4uCpHCL6vKd3xHIZTl+INMOjPyIAGgQaKlbJYpexLJ6wcs4LLZhehD+dhoISigBOa0ceMqR0F5eBFRDRUbz/i253qhi5jp/JV5otOY0Z0CZiXDcsP+nx8CG9aXKFgYnSinA5qRLvOWi9rh20kpB4sURq5NqiWAlsjo7tGiPhiL5HehlNsGw6RCdXRw4wgO/3NrmO7jXj2Wmsoqx957m0yYC0tgKN5/Sh+GzD504NwY3ZxQqZ1kyE1HS8OkCARUhJ2Zc/Uc2Ka+0xwJqjZLylfWBXsgZljg8Hv4papJ+gHm3CLyMgoo7NID1lbPlcE2hhT3Ia5kDME9D8o0JpaTV+4YwqB0VpKzRQA4xPkphsd4FK4ZxRLlgKtS+HrdMOCdo/nhBDZf2eUKdwfFYrSTdtaynbiw37uX3IxyHUzuHdhuEOekonrHFvjT9yQzCItIbDNvwI0=
  file_glob: true
  file: clpeak-*.zip
  skip_cleanup: true
  on:
    repo: krrishnarraj/clpeak
    tags: true
